// react/routed-react/src/components/UsersList/UsersList.js
import React, { Component } from 'react';
import './UsersList.css';

class UsersList extends Component {
	constructor(props) {
		super(props);

		this.state = {
			users: this.props.users
		};



		this.removeFromArray = this.RemoveFromArray.bind(this);
	}

	RemoveFromArray(e) {
		let index = e.target.value;
		let array = this.state.users;
		console.log('idx', index)
		if (index != -1) {
			console.log(+index, 1)
			array.splice(+index, 1);
			this.setState({users: array});
		}
		return false;
	}

	render() {
		let users;
		let saveThis = this;

		if (this.state.users.length > 0) {
			users = this.state.users.map(function (item, index) {
				return (
					<div key={index}
						className={`user-item
							${item.admin ? 'bg-green' : ''}
							${item.manager ? 'bg-aqua' : ''}
							${item.superman ? 'bg-red' : ''}`}>

						<h3>{item.name}</h3>
						<p>Phone: {item.phone}</p>
						<p>Email: {item.email}</p>
						<br/>
						<p>Driver: {item.driver}</p>
						<p>Phone: {item.phoneDriver}</p>
						<div className="actions-list">
							<button className="edit-btn"/>
							<button onClick={saveThis.removeFromArray} value={index} className="remove-btn"/>
						</div>
					</div>

				);
			});
		}

		return (
			<div className="users-list">
				{users}
			</div>
		);

	}
}

export default UsersList;

// angular/src/app/users-list/users-list.component.ts
import { Component, OnInit } from '@angular/core';
import { UsersService } from '../users.service';

@Component({
  selector   : 'app-users-list',
  templateUrl: './users-list.component.html',
  styleUrls  : ['./users-list.component.styl']
})
export class UsersListComponent implements OnInit {
  users: any;

  constructor(
    private usersService: UsersService
  ) {
  }

  ngOnInit() {
    setTimeout(() => this.users = this.usersService.getUsers(), 1000);
  }


  removeFromArray(array, value) {
    let idx = array.indexOf(value);
    if (idx != -1) {
      return array.splice(idx, 1);
    }
    return false;
  }
}

<div class="users-list">
  <div *ngFor="let user of users"
       class="user-item"
       [ngClass]="{
       'bg-green':user.admin,
       'bg-aqua':user.manager,
       'bg-red':user.superman
       }">
    <h3>{{user.name}}</h3>
    <p>Phone: {{user.phone}}</p>
    <p>Email: {{user.email}}</p>
    <br>
    <p>Driver: {{user.driver}}</p>
    <p>Phone: {{user.phoneDriver}}</p>
    <div class="actions-list">
      <button class="edit-btn"></button>
      <button (click)="removeFromArray(users, user)" class="remove-btn"></button>
    </div>
  </div>
</div>
