// react/routed-react/src/App.js
import React, { Component } from 'react';
import logo from './assets/img/logo.png';
import './App.css';
import UsersList from './components/UsersList/UsersList'

class App extends Component {
	constructor(props) {
		super(props);
		this.state = {
			user: {
				name: 'Nick',
			}
		};
	};

	render() {

		return (
			<div className="wrapper">
				<header>
					<img className="logo" src={logo} alt=""/>
				</header>
				<nav>
					<div>Welcome back, {this.state.user.name}!</div>
					<div className="align-center">
						<button>{' << '}</button>
						October 18, 2017
						<button>{' >> '}</button>
					</div>
					<div>
						<div className="tools-list">
							<button className="add-btn"/>
							<button className="search-btn"/>
							<button className="users-btn"/>
							<button className="settings-btn"/>
							<button className="logout-btn"/>
						</div>
					</div>
				</nav>
				<main>
					<UsersList/>
				</main>
			</div>

		);
	}

}

export default App;

// angular/src/app/app.component.ts
import { Component, OnInit } from '@angular/core';
import { UsersService } from './users.service';

@Component({
  selector   : 'app-root',
  templateUrl: './app.component.html',
  styleUrls  : ['./app.component.styl']
})
export class AppComponent implements OnInit {
  title = 'app works!';

  constructor(private usersService: UsersService) {
  }

  ngOnInit() {
    console.log(this.usersService.user.name)
  }
}

<div class="wrapper">
  <header>
    <img class="logo" src="assets/img/logo.png"/>
  </header>
  <nav>
    <div>Welcome back, {{usersService.user.name}}!</div>
    <div class="align-center"><button><<</button> October 18, 2017 <button>>></button></div>
    <div>
      <div class="tools-list">
        <button class="add-btn"></button>
        <button class="search-btn"></button>
        <button class="users-btn"></button>
        <button class="settings-btn"></button>
        <button class="logout-btn"></button>
      </div>
    </div>
  </nav>
  <main>
    <app-users-list></app-users-list>
  </main>
</div>
